import { State } from './types';

export const INDIAN_STATES: State[] = [
  {
    id: 1,
    name: 'Andhra Pradesh',
    description: 'Known for Tirupati, beautiful beaches, and Araku Valley. Rich in cultural heritage.',
    longDescription: 'Andhra Pradesh, on the southeastern coast, is a state of deep religious significance, with the Tirumala Venkateswara Temple being a major pilgrimage site. It also features beautiful beaches and the picturesque hill station of Araku Valley.',
    bestTimeToVisit: 'October to February',
    imageUrl: 'https://picsum.photos/seed/andhrapradesh/400/300',
    topTouristPlaces: [
      { name: 'Tirumala Venkateswara Temple', description: 'One of the most visited Hindu pilgrimage sites in the world, located in the hill town of Tirumala.' },
      { name: 'Araku Valley', description: 'A scenic hill station known for its coffee plantations, waterfalls, and tribal culture.' },
      { name: 'Borra Caves', description: 'Stunning limestone caves considered among the largest and deepest in India.' },
      { name: 'Visakhapatnam Beaches', description: 'A series of beautiful beaches including Ramakrishna Beach and Rishikonda Beach.' },
      { name: 'Lepakshi', description: 'Famous for its Veerabhadra temple with intricate sculptures and a large Nandi bull statue.' },
      { name: 'Srisailam Temple', description: 'A prominent pilgrimage center dedicated to Lord Shiva, located on the banks of the Krishna River.' },
      { name: 'Pulicat Lake', description: 'The second largest brackish water lagoon in India, a haven for birdwatchers.' },
      { name: 'Belum Caves', description: 'The longest and second largest cave system in the Indian subcontinent, known for its stalactite and stalagmite formations.' },
      { name: 'Rajahmundry', description: 'A major city on the banks of the Godavari River, known for its ghats and temples.' },
      { name: 'Gandikota', description: 'Often referred to as the "Grand Canyon of India," known for its stunning gorge formed by the Penna river.' },
    ],
  },
  {
    id: 2,
    name: 'Arunachal Pradesh',
    description: 'Land of the dawn-lit mountains, known for its pristine beauty and diverse tribal culture.',
    longDescription: "Arunachal Pradesh, in the northeastern tip of India, is a breathtakingly beautiful state with snow-capped Himalayas, lush valleys, and dense forests. It's home to numerous indigenous tribes and ancient Buddhist monasteries like Tawang.",
    bestTimeToVisit: 'October to April',
    imageUrl: 'https://picsum.photos/seed/arunachalpradesh/400/300',
    topTouristPlaces: [
        { name: 'Tawang Monastery', description: 'The largest monastery in India and the second largest in the world, offering panoramic views.' },
        { name: 'Ziro Valley', description: 'A picturesque valley, home to the Apatani tribe, known for its pine hills and rice fields.' },
        { name: 'Sela Pass', description: 'A high-altitude mountain pass connecting Tawang to the rest of India, with a stunning paradise lake.' },
        { name: 'Namdapha National Park', description: 'A biodiversity hotspot, it is the third largest national park in India.' },
        { name: 'Bomdila', description: 'A scenic town offering views of Kangto and Gorichen Peaks, with a beautiful monastery.' },
        { name: 'Dirang', description: 'Known for its hot water springs, apple orchards, and the medieval Dirang Dzong fort.' },
        { name: 'Roing', description: 'A picturesque town by the Dibang River, with attractions like Mehao Lake and Mayudia pass.' },
        { name: 'Itanagar', description: 'The state capital, home to the Ita Fort and Ganga Lake (Gyakar Sinyi).' },
        { name: 'Mechuka', description: 'Often called the "Forbidden Valley of Arunachal," known for its pristine landscapes and the 400-year-old Samten Yongcha Monastery.' },
        { name: 'Golden Pagoda (Namsai)', description: 'A beautiful Burmese-style Buddhist temple known for its serene atmosphere.' },
    ],
  },
  {
    id: 3,
    name: 'Assam',
    description: 'Gateway to Northeast India, famous for tea gardens, the Brahmaputra River, and Kaziranga.',
    longDescription: 'Assam is a land of rolling plains and dense forests, dominated by the mighty Brahmaputra River. It is world-famous for its tea and is home to the one-horned rhinoceros in Kaziranga National Park.',
    bestTimeToVisit: 'October to April',
    imageUrl: 'https://picsum.photos/seed/assam/400/300',
    topTouristPlaces: [
        { name: 'Kaziranga National Park', description: 'A UNESCO World Heritage Site, home to two-thirds of the world\'s great one-horned rhinoceroses.' },
        { name: 'Majuli Island', description: 'The largest river island in the world, located on the Brahmaputra River, and a center of Neo-Vaishnavite culture.' },
        { name: 'Kamakhya Temple', description: 'A major Hindu pilgrimage site in Guwahati, dedicated to the mother goddess Kamakhya.' },
        { name: 'Manas National Park', description: 'A UNESCO World Heritage Site, known for its rare and endangered endemic wildlife such as the Assam roofed turtle and golden langur.' },
        { name: 'Sivasagar', description: 'The historical capital of the Ahom Kingdom, with ancient temples and man-made tanks.' },
        { name: 'Guwahati', description: 'The largest city in Assam and a gateway to the Northeast, with several temples and the Brahmaputra riverfront.' },
        { name: 'Hajo', description: 'An ancient pilgrimage center for Hindus, Muslims, and Buddhists.' },
        { name: 'Umananda Island', description: 'The smallest inhabited river island in the world, home to the Umananda Temple.' },
        { name: 'Dibrugarh', description: 'Known as the "Tea City of India," surrounded by lush tea estates.' },
        { name: 'Pobitora Wildlife Sanctuary', description: 'Known for having the highest density of one-horned rhinos in the world.' },
    ],
  },
  {
    id: 4,
    name: 'Bihar',
    description: 'A land of ancient history, home to the Mahabodhi Temple and Nalanda University ruins.',
    longDescription: 'Bihar has a rich history as the center of the Maurya and Gupta empires. It is the place where Buddhism originated and is home to major pilgrimage sites like Bodh Gaya, where the Buddha attained enlightenment.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/bihar/400/300',
    topTouristPlaces: [
      { name: 'Mahabodhi Temple, Bodh Gaya', description: 'A UNESCO World Heritage Site where Gautama Buddha is said to have attained Enlightenment.' },
      { name: 'Nalanda University Ruins', description: 'The archaeological remains of a great monastic-cum-scholastic institution from the 5th to the 13th century.' },
      { name: 'Rajgir', description: 'An ancient city known for its hot springs, Vishwa Shanti Stupa, and sites related to Buddha and Mahavira.' },
      { name: 'Vaishali', description: 'An important archaeological site and pilgrimage center for both Buddhists and Jains.' },
      { name: 'Patna Sahib Gurudwara', description: 'One of the holiest sites for Sikhs, marking the birthplace of Guru Gobind Singh.' },
      { name: 'Sher Shah Suri Tomb', description: 'A magnificent mausoleum in Sasaram, an example of Indo-Islamic architecture.' },
      { name: 'Vikramshila University Ruins', description: 'The remains of another important ancient Buddhist university.' },
      { name: 'Barabar Caves', description: 'The oldest surviving rock-cut caves in India, dating from the Maurya Empire.' },
      { name: 'Pawapuri', description: 'A holy site for Jains, where Lord Mahavira attained Nirvana.' },
      { name: 'Valmiki National Park', description: 'The only national park in Bihar, located in the West Champaran district.' },
    ],
  },
  {
    id: 5,
    name: 'Chhattisgarh',
    description: 'A heavily forested state known for its temples, waterfalls, and unique tribal culture.',
    longDescription: 'Chhattisgarh is a treasure trove of natural beauty, with dense forests, scenic waterfalls like Chitrakote, and ancient caves. It is also home to a large tribal population, each with its own rich cultural traditions.',
    bestTimeToVisit: 'September to March',
    imageUrl: 'https://picsum.photos/seed/chhattisgarh/400/300',
    topTouristPlaces: [
        { name: 'Chitrakote Falls', description: 'Often called the "Niagara Falls of India," this is the widest waterfall in the country.' },
        { name: 'Tirathgarh Falls', description: 'A spectacular block-type waterfall dropping 91 meters in a single drop.' },
        { name: 'Kanger Valley National Park', description: 'A dense forest area with rich biodiversity, limestone caves, and waterfalls.' },
        { name: 'Bastar', description: 'A tribal region known for its unique culture, handicrafts, and vibrant festivals like the Bastar Dussehra.' },
        { name: 'Bhoramdeo Temple', description: 'Known as the "Khajuraho of Chhattisgarh" for its erotic sculptures.' },
        { name: 'Sirpur', description: 'An important archaeological site with ancient temples and Buddhist monastery ruins.' },
        { name: 'Kotumsar Cave', description: 'One of the most biologically explored caves in India, known for its blind fish species.' },
        { name: 'Mainpat', description: 'A charming hill station known as the "Shimla of Chhattisgarh" and home to a Tibetan settlement.' },
        { name: 'Danteshwari Temple', description: 'A revered Shakti Peeth in Dantewada, dedicated to the goddess Danteshwari.' },
        { name: 'Raipur', description: 'The capital city, featuring attractions like the Mahant Ghasidas Museum and Nandan Van Zoo.' },
    ],
  },
  {
    id: 6,
    name: 'Goa',
    description: 'Famous for its pristine beaches, vibrant nightlife, Portuguese heritage, and relaxed atmosphere.',
    longDescription: 'Goa is India’s pocket-sized paradise. Known for its endless beaches, vibrant nightlife, delicious seafood, and colonial-era architecture, it offers a unique blend of Indian and Portuguese cultures.',
    bestTimeToVisit: 'November to February',
    imageUrl: 'https://picsum.photos/seed/goa/400/300',
    topTouristPlaces: [
        { name: 'Calangute Beach', description: 'The largest beach in North Goa, often called the "Queen of Beaches."' },
        { name: 'Basilica of Bom Jesus', description: 'A UNESCO World Heritage Site in Old Goa, holding the mortal remains of St. Francis Xavier.' },
        { name: 'Fort Aguada', description: 'A well-preserved 17th-century Portuguese fort with a lighthouse, offering stunning sea views.' },
        { name: 'Dudhsagar Falls', description: 'A magnificent four-tiered waterfall located on the Mandovi River, meaning "Sea of Milk."' },
        { name: 'Palolem Beach', description: 'A picturesque crescent-shaped beach in South Goa, known for its calm waters and scenic beauty.' },
        { name: 'Anjuna Flea Market', description: 'A famous Wednesday market offering a variety of goods, from handicrafts to clothing.' },
        { name: 'Baga Beach', description: 'Known for its vibrant nightlife, water sports, and beach shacks.' },
        { name: 'Old Goa (Velha Goa)', description: 'The former capital of Portuguese India, filled with historic churches and cathedrals.' },
        { name: 'Tito\'s Lane', description: 'A famous lane in Baga known for its bustling nightlife with numerous clubs and bars.' },
        { name: 'Spice Plantations', description: 'Explore lush plantations in Ponda to learn about various spices and enjoy a traditional Goan meal.' },
    ],
  },
  {
    id: 7,
    name: 'Gujarat',
    description: 'Land of Gandhi, with diverse landscapes from Rann of Kutch to Gir forest lions.',
    longDescription: 'Gujarat offers a diverse range of attractions, from the white salt desert of the Rann of Kutch to the last abode of the Asiatic lion in Gir National Park. It also has a rich history and vibrant cultural festivals.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/gujarat/400/300',
    topTouristPlaces: [
        { name: 'Gir National Park', description: 'The only place in the world where you can see Asiatic lions in their natural habitat.' },
        { name: 'Rann of Kutch', description: 'One of the largest salt deserts in the world, famous for the Rann Utsav festival.' },
        { name: 'Statue of Unity', description: 'The world\'s tallest statue, dedicated to Sardar Vallabhbhai Patel.' },
        { name: 'Somnath Temple', description: 'One of the most sacred of the twelve Jyotirlinga shrines of Lord Shiva.' },
        { name: 'Dwarkadhish Temple', description: 'A major Hindu pilgrimage site dedicated to Lord Krishna, part of the Char Dham yatra.' },
        { name: 'Sabarmati Ashram', description: 'The former residence of Mahatma Gandhi, located on the banks of the Sabarmati river.' },
        { name: 'Rani ki Vav', description: 'An intricately constructed stepwell and a UNESCO World Heritage Site in Patan.' },
        { name: 'Akshardham Temple, Gandhinagar', description: 'A massive temple complex dedicated to Swaminarayan, known for its stunning architecture.' },
        { name: 'Champaner-Pavagadh Archaeological Park', description: 'A UNESCO World Heritage Site with historical and archaeological treasures.' },
        { name: 'Ahmedabad Old City', description: 'India\'s first UNESCO World Heritage City, known for its pols (traditional housing clusters) and rich architecture.' },
    ],
  },
  {
    id: 8,
    name: 'Haryana',
    description: 'A vibrant state known for its rich folklore, historical battles like Panipat, and modern cities.',
    longDescription: 'Haryana has a proud history, being the site of the epic Mahabharata battle in Kurukshetra. Today, it is a blend of ancient heritage and modern development, with cities like Gurugram being major IT hubs.',
    bestTimeToVisit: 'September to March',
    imageUrl: 'https://picsum.photos/seed/haryana/400/300',
    topTouristPlaces: [
      { name: 'Kurukshetra', description: 'The land of the Mahabharata, with sacred sites like Brahma Sarovar and Jyotisar.' },
      { name: 'Sultanpur National Park', description: 'A bird sanctuary ideal for bird watching, especially during winter.' },
      { name: 'Yadavindra Gardens, Pinjore', description: 'A historic 17th-century Mughal garden with beautiful fountains and terraced lawns.' },
      { name: 'Surajkund', description: 'An ancient reservoir and the site of the famous annual Surajkund International Crafts Mela.' },
      { name: 'Morni Hills', description: 'The only hill station in Haryana, offering trekking and boating opportunities.' },
      { name: 'Kingdom of Dreams', description: 'A spectacular live entertainment and theatre destination in Gurugram.' },
      { name: 'Badkhal Lake', description: 'A scenic lake in Faridabad, nestled in the Aravalli Hills.' },
      { name: 'Sheikh Chilli\'s Tomb', description: 'A beautiful mausoleum in Thanesar, with Mughal architectural influences.' },
      { name: 'Panipat', description: 'Known for three historical battles, with sites like the Panipat Museum and Kabuli Bagh Mosque.' },
      { name: 'Star Monument (Samadhi of Tara Chand ji Maharaj)', description: 'A unique star-shaped monument in Bhiwani.' },
    ],
  },
  {
    id: 9,
    name: 'Himachal Pradesh',
    description: 'Mountain state with snow-capped peaks, adventure sports, and spiritual retreats.',
    longDescription: 'Nestled in the Himalayas, Himachal Pradesh is a destination for adventure lovers and peace seekers alike. It offers trekking, skiing, and stunning landscapes in places like Shimla, Manali, and Dharamshala.',
    bestTimeToVisit: 'March to June, December to February',
    imageUrl: 'https://picsum.photos/seed/himachalpradesh/400/300',
    topTouristPlaces: [
        { name: 'Shimla', description: 'The capital city, known for its colonial architecture, The Ridge, and Mall Road.' },
        { name: 'Manali', description: 'A popular backpacking and honeymoon destination, gateway to Solang Valley and Rohtang Pass.' },
        { name: 'Dharamshala & McLeod Ganj', description: 'Home to the Dalai Lama and a large Tibetan community, a spiritual and scenic retreat.' },
        { name: 'Spiti Valley', description: 'A cold desert mountain valley known for its stark landscapes, monasteries, and trekking routes.' },
        { name: 'Kasol', description: 'A Himalayan hotspot for backpackers, situated in the Parvati Valley.' },
        { name: 'Dalhousie', description: 'A charming hill station with colonial-era buildings and panoramic mountain views.' },
        { name: 'Khajjiar', description: 'Often called the "Mini Switzerland of India" for its picturesque meadow and lake.' },
        { name: 'Great Himalayan National Park', description: 'A UNESCO World Heritage Site, home to diverse flora and fauna.' },
        { name: 'Kullu', description: 'Famous for its Dussehra festival, temples, and beautiful valleys.' },
        { name: 'Bir Billing', description: 'Considered one of the best sites in the world for paragliding.' },
    ],
  },
  {
    id: 10,
    name: 'Jharkhand',
    description: 'Known as the "Land of Forests," rich in minerals, waterfalls, and tribal culture.',
    longDescription: 'Jharkhand is a state of immense natural beauty, with rolling hills, dense forests, and powerful waterfalls. It has a rich tribal heritage and is a significant producer of mineral resources in India.',
    bestTimeToVisit: 'October to February',
    imageUrl: 'https://picsum.photos/seed/jharkhand/400/300',
    topTouristPlaces: [
      { name: 'Dassam Falls', description: 'A spectacular waterfall where the Kanchi River falls from a height of 44 meters.' },
      { name: 'Jonha Falls', description: 'Also known as Gautamdhara, a scenic waterfall with a nearby temple and ashram.' },
      { name: 'Hundru Falls', description: 'One of the highest waterfalls in the state, created by the Subarnarekha River.' },
      { name: 'Betla National Park', description: 'A diverse park with a wide variety of wildlife, including tigers and elephants.' },
      { name: 'Parasnath Hill', description: 'The highest peak in Jharkhand and a major pilgrimage center for Jains.' },
      { name: 'Deoghar', description: 'A holy city with the Baidyanath Temple, one of the twelve Jyotirlingas.' },
      { name: 'Netarhat', description: 'A beautiful hill station known as the "Queen of Chotanagpur," famous for its sunrises and sunsets.' },
      { name: 'Ranchi', description: 'The capital city, with attractions like Ranchi Lake, Rock Garden, and Jagannath Temple.' },
      { name: 'Tagore Hill', description: 'A scenic hilltop in Ranchi associated with the writer Rabindranath Tagore.' },
      { name: 'Jubilee Park, Jamshedpur', description: 'A large urban park inspired by the Vrindavan Gardens of Mysore.' },
    ],
  },
  {
    id: 11,
    name: 'Karnataka',
    description: 'A blend of ancient ruins in Hampi, modern city life in Bengaluru, and pristine nature.',
    longDescription: 'Karnataka is a diverse state with the tech hub of Bengaluru, the majestic ruins of the Vijayanagara Empire in Hampi, beautiful palaces in Mysuru, and the lush green hills of the Western Ghats.',
    bestTimeToVisit: 'October to April',
    imageUrl: 'https://picsum.photos/seed/karnataka/400/300',
    topTouristPlaces: [
        { name: 'Hampi', description: 'A UNESCO World Heritage Site with captivating ruins of the Vijayanagara Empire.' },
        { name: 'Mysore Palace', description: 'The historical palace of the Wadiyar dynasty, known for its magnificent architecture.' },
        { name: 'Coorg (Kodagu)', description: 'A picturesque hill station famous for its coffee plantations, mist-covered hills, and waterfalls.' },
        { name: 'Bengaluru', description: 'The "Silicon Valley of India," known for its pleasant climate, parks, and vibrant nightlife.' },
        { name: 'Gokarna', description: 'A serene temple town with pristine beaches like Om Beach and Kudle Beach.' },
        { name: 'Jog Falls', description: 'India\'s second-highest plunge waterfall, a spectacular sight during the monsoon.' },
        { name: 'Badami, Aihole & Pattadakal', description: 'A complex of ancient temples showcasing Chalukyan architecture.' },
        { name: 'Chikmagalur', description: 'Known as the "Coffee Land of Karnataka," a tranquil retreat in the Western Ghats.' },
        { name: 'Udupi', description: 'Famous for its Krishna Temple and as the origin of the popular Udupi cuisine.' },
        { name: 'Nagarhole National Park', description: 'A premier wildlife reserve, part of the Nilgiri Biosphere Reserve.' },
    ],
  },
  {
    id: 12,
    name: 'Kerala',
    description: 'God\'s Own Country, famous for its serene backwaters, palm-fringed beaches, and tea plantations.',
    longDescription: 'Kerala is a tropical paradise known for its tranquil backwaters explored on houseboats, stunning beaches, and the rolling tea gardens of Munnar. It is also a center for Ayurvedic treatments.',
    bestTimeToVisit: 'September to March',
    imageUrl: 'https://picsum.photos/seed/kerala/400/300',
    topTouristPlaces: [
        { name: 'Alleppey (Alappuzha) Backwaters', description: 'Famous for its houseboat cruises on serene backwaters lined with palm trees.' },
        { name: 'Munnar', description: 'A beautiful hill station renowned for its sprawling tea plantations and lush greenery.' },
        { name: 'Kochi (Cochin)', description: 'A vibrant city with a rich history, known for Fort Kochi, Chinese fishing nets, and colonial architecture.' },
        { name: 'Thekkady (Periyar National Park)', description: 'A major wildlife sanctuary, home to elephants, tigers, and a rich variety of birds.' },
        { name: 'Wayanad', description: 'A lush district in the Western Ghats known for its spice plantations, caves, and waterfalls.' },
        { name: 'Kovalam', description: 'A famous beach town with three crescent-shaped beaches.' },
        { name: 'Varkala', description: 'A stunning coastal town known for its cliff-side beaches and mineral springs.' },
        { name: 'Kumarakom', description: 'A tranquil backwater destination on Vembanad Lake, famous for its bird sanctuary.' },
        { name: 'Marari Beach', description: 'A pristine and peaceful beach, perfect for a relaxing getaway.' },
        { name: 'Athirappilly Falls', description: 'The largest waterfall in Kerala, often referred to as the "Niagara of India."' },
    ],
  },
  {
    id: 13,
    name: 'Madhya Pradesh',
    description: 'The "Heart of India," with national parks like Kanha, and historical sites like Khajuraho.',
    longDescription: 'Madhya Pradesh is home to a rich tapestry of history, wildlife, and culture. It boasts ancient temples in Khajuraho, magnificent forts, and is a prime destination for tiger sightings in its numerous national parks.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/madhyapradesh/400/300',
    topTouristPlaces: [
        { name: 'Khajuraho Group of Monuments', description: 'A UNESCO World Heritage Site famous for its stunning temples with intricate and erotic sculptures.' },
        { name: 'Bandhavgarh National Park', description: 'Known for having one of the highest densities of Bengal tigers in the world.' },
        { name: 'Kanha National Park', description: 'A lush forest that inspired Rudyard Kipling\'s "The Jungle Book," a prime tiger reserve.' },
        { name: 'Sanchi Stupa', description: 'A major Buddhist complex, famous for its Great Stupa, commissioned by Emperor Ashoka.' },
        { name: 'Gwalior Fort', description: 'A magnificent hill fort that has been the scene of many historical events.' },
        { name: 'Orchha', description: 'A historic town on the banks of the Betwa River, known for its palaces, temples, and cenotaphs.' },
        { name: 'Pachmarhi', description: 'The only hill station in Madhya Pradesh, a serene getaway in the Satpura Range.' },
        { name: 'Ujjain', description: 'An ancient and holy city, one of the sites for the Kumbh Mela, with the famous Mahakaleshwar Jyotirlinga.' },
        { name: 'Mandu', description: 'A ruined city celebrated for its fine architecture and the love story of Prince Baz Bahadur and Rani Roopmati.' },
        { name: 'Bhopal', description: 'The "City of Lakes," with attractions like the Upper Lake, Lower Lake, and Van Vihar National Park.' },
    ],
  },
  {
    id: 14,
    name: 'Maharashtra',
    description: 'Home to the bustling metropolis of Mumbai, ancient caves of Ajanta and Ellora, and scenic hill stations.',
    longDescription: 'Maharashtra offers a dynamic mix of attractions, from the fast-paced life of Mumbai to the ancient rock-cut caves of Ajanta and Ellora. The Western Ghats provide stunning landscapes and numerous forts.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/maharashtra/400/300',
    topTouristPlaces: [
        { name: 'Mumbai', description: 'The vibrant capital city, home to the Gateway of India, Marine Drive, Bollywood, and bustling markets.' },
        { name: 'Ajanta and Ellora Caves', description: 'UNESCO World Heritage Sites with magnificent rock-cut caves showcasing ancient Indian art and architecture.' },
        { name: 'Pune', description: 'Known as the "Oxford of the East," a cultural hub with historical sites like Shaniwar Wada.' },
        { name: 'Mahabaleshwar', description: 'A popular hill station in the Western Ghats, known for its viewpoints, strawberries, and serene lakes.' },
        { name: 'Lonavala and Khandala', description: 'Twin hill stations famous for their scenic beauty, forts, and waterfalls, especially during monsoon.' },
        { name: 'Shirdi', description: 'A major pilgrimage site for devotees of Sai Baba.' },
        { name: 'Nashik', description: 'A holy city on the banks of the Godavari River, known for its temples and vineyards.' },
        { name: 'Tadoba Andhari Tiger Reserve', description: 'One of the best places in India for tiger sightings.' },
        { name: 'Aurangabad', description: 'A historic city that serves as a base for visiting Ajanta and Ellora, with sites like Bibi Ka Maqbara.' },
        { name: 'Matheran', description: 'An eco-sensitive hill station where vehicles are banned, offering a peaceful retreat.' },
    ],
  },
  {
    id: 15,
    name: 'Manipur',
    description: 'The "Jewel of India," known for its classical dance, floating Loktak Lake, and vibrant culture.',
    longDescription: 'Manipur is a land of gentle hills and valleys, famous for the floating islands of Loktak Lake and the graceful Manipuri dance. Its unique culture and natural beauty make it a hidden gem.',
    bestTimeToVisit: 'October to May',
    imageUrl: 'https://picsum.photos/seed/manipur/400/300',
    topTouristPlaces: [
        { name: 'Loktak Lake', description: 'The largest freshwater lake in Northeast India, famous for its floating phumdis (heterogeneous mass of vegetation).' },
        { name: 'Keibul Lamjao National Park', description: 'The world\'s only floating national park, home to the endangered Sangai deer.' },
        { name: 'Imphal', description: 'The capital city, featuring the Kangla Fort, Ima Keithel (Women\'s Market), and war cemeteries.' },
        { name: 'Dzukou Valley', description: 'A stunning valley on the border of Manipur and Nagaland, known for its seasonal flowers.' },
        { name: 'Andro Village', description: 'A cultural village showcasing traditional Manipuri lifestyle, pottery, and a cultural museum.' },
        { name: 'Moreh', description: 'A bustling commercial town on the India-Myanmar border, offering a glimpse into cross-border trade.' },
        { name: 'Ukhrul', description: 'A picturesque hill town known for its natural beauty and the Shirui Lily.' },
        { name: 'Singda Dam', description: 'The highest mud dam in the world, offering picturesque views and a popular picnic spot.' },
        { name: 'Tharon Cave', description: 'An intriguing 655-meter-long cave system in the Tamenglong district.' },
        { name: 'Leimaram Waterfall', description: 'A beautiful three-tiered waterfall located in the Senapati district.' },
    ],
  },
  {
    id: 16,
    name: 'Meghalaya',
    description: 'The "Abode of Clouds," famous for its living root bridges, stunning waterfalls, and lush landscapes.',
    longDescription: 'Meghalaya is one of the wettest places on Earth, resulting in breathtakingly green landscapes, powerful waterfalls, and the unique, man-made living root bridges of Cherrapunji.',
    bestTimeToVisit: 'October to June',
    imageUrl: 'https://picsum.photos/seed/meghalaya/400/300',
    topTouristPlaces: [
        { name: 'Double Decker Living Root Bridge', description: 'A unique two-tiered bridge made from the roots of living fig trees in Cherrapunji.' },
        { name: 'Mawlynnong Village', description: 'Famed as "Asia\'s Cleanest Village," known for its cleanliness and natural beauty.' },
        { name: 'Dawki (Umngot River)', description: 'A town known for the crystal clear waters of the Umngot River, offering a surreal boating experience.' },
        { name: 'Cherrapunji (Sohra)', description: 'One of the wettest places on earth, famous for its waterfalls like Nohkalikai Falls and Seven Sisters Falls.' },
        { name: 'Shillong', description: 'The capital city, known as the "Scotland of the East," with attractions like Umiam Lake and Elephant Falls.' },
        { name: 'Mawsynram', description: 'Reportedly the wettest place on Earth, with stunning landscapes and the Mawjymbuin Cave.' },
        { name: 'Nohkalikai Falls', description: 'The tallest plunge waterfall in India, offering a spectacular view.' },
        { name: 'Umiam Lake', description: 'A vast man-made lake, a popular spot for water sports and picnics.' },
        { name: 'Garo Hills', description: 'A region known for its rich biodiversity, Nokrek Biosphere Reserve, and Siju Caves.' },
        { name: 'Laitlum Canyons', description: 'Offering breathtaking panoramic views of the surrounding green hills and valleys.' },
    ],
  },
  {
    id: 17,
    name: 'Mizoram',
    description: 'A land of rolling hills and serene landscapes, known for its vibrant festivals and friendly people.',
    longDescription: 'Mizoram is a beautiful state in Northeast India with lush hills, deep valleys, and a pleasant climate. The Mizo people are known for their hospitality and colorful cultural festivals.',
    bestTimeToVisit: 'November to March',
    imageUrl: 'https://picsum.photos/seed/mizoram/400/300',
    topTouristPlaces: [
      { name: 'Aizawl', description: 'The capital city, perched on ridges, offering panoramic views and cultural sites like the Mizoram State Museum.' },
      { name: 'Reiek', description: 'A scenic mountain peak near Aizawl, offering trekking and stunning views of the surrounding valleys.' },
      { name: 'Phawngpui (Blue Mountain)', description: 'The highest peak in Mizoram, part of a national park, known for its beautiful landscapes and orchids.' },
      { name: 'Vantawng Falls', description: 'The highest waterfall in Mizoram, located in a lush green valley.' },
      { name: 'Murlen National Park', description: 'A dense park known for its rich variety of flora and fauna, often compared to the Amazon forest.' },
      { name: 'Tamdil Lake', description: 'A beautiful man-made lake surrounded by forests, ideal for boating and picnics.' },
      { name: 'Champhai', description: 'A commercial town with stunning views of the Myanmar hills and vast rice fields.' },
      { name: 'Hmuifang', description: 'A tranquil hill station covered with virgin forests, offering a peaceful retreat.' },
      { name: 'Lunglei', description: 'The second largest city, offering scenic beauty and a glimpse into Mizo culture.' },
      { name: 'Solomon\'s Temple', description: 'A beautiful white temple in Aizawl, a unique architectural landmark.' },
    ],
  },
  {
    id: 18,
    name: 'Nagaland',
    description: 'Home to diverse indigenous tribes, famous for the Hornbill Festival and unique cultural experiences.',
    longDescription: 'Nagaland offers a fascinating glimpse into the life of its 16 major tribes, each with its own customs and traditions. The annual Hornbill Festival is a spectacular showcase of this rich cultural diversity.',
    bestTimeToVisit: 'October to May',
    imageUrl: 'https://picsum.photos/seed/nagaland/400/300',
    topTouristPlaces: [
        { name: 'Dzukou Valley', description: 'A stunning valley on the border of Nagaland and Manipur, famous for its seasonal flowers and trekking trails.' },
        { name: 'Kohima', description: 'The hilly capital, known for the Kohima War Cemetery and the State Museum.' },
        { name: 'Kisama Heritage Village', description: 'The venue for the annual Hornbill Festival, showcasing the traditions of Naga tribes.' },
        { name: 'Mokokchung', description: 'A lively town and the cultural heartland of the Ao Naga tribe.' },
        { name: 'Mon', description: 'The land of the Konyak Nagas, known for their tattooed faces and headhunting history.' },
        { name: 'Khonoma Village', description: 'India\'s first green village, known for its community conservation projects and rich history.' },
        { name: 'Tuophema Village', description: 'A tourist village offering an authentic experience of Naga culture with traditional huts.' },
        { name: 'Japfu Peak', description: 'The second highest peak in Nagaland, offering stunning views and rhododendron forests.' },
        { name: 'Dimapur', description: 'The commercial hub of Nagaland, with historical sites like the Kachari Ruins.' },
        { name: 'Pfutsero', description: 'The coldest inhabited place in Nagaland, known for its scenic beauty and apple orchards.' },
    ],
  },
  {
    id: 19,
    name: 'Odisha',
    description: 'Known for its ancient temples in Bhubaneswar and Puri, classical Odissi dance, and Chilika Lake.',
    longDescription: 'Odisha has a rich cultural and architectural heritage, with grand temples like the Konark Sun Temple and Jagannath Temple in Puri. It is also home to Chilika Lake, a vast brackish water lagoon.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/odisha/400/300',
    topTouristPlaces: [
        { name: 'Puri Jagannath Temple & Beach', description: 'A major Hindu pilgrimage site and a popular beach destination.' },
        { name: 'Konark Sun Temple', description: 'A UNESCO World Heritage Site, an architectural marvel in the form of a colossal chariot.' },
        { name: 'Bhubaneswar', description: 'The "Temple City of India," with hundreds of temples like Lingaraj and Mukteshwar.' },
        { name: 'Chilika Lake', description: 'Asia\'s largest brackish water lagoon, a haven for migratory birds and dolphins.' },
        { name: 'Simlipal National Park', description: 'A vast national park and tiger reserve with beautiful waterfalls.' },
        { name: 'Udayagiri and Khandagiri Caves', description: 'Ancient rock-cut caves with ornate carvings, built for Jain monks.' },
        { name: 'Dhauli Giri Shanti Stupa', description: 'A Buddhist peace pagoda on the site of the ancient Kalinga War.' },
        { name: 'Gopalpur-on-Sea', description: 'A serene beach resort on the coast of the Bay of Bengal.' },
        { name: 'Ratnagiri-Lalitgiri-Udayagiri', description: 'The "Diamond Triangle" of Buddhist monasteries and stupas.' },
        { name: 'Bhitarkanika National Park', description: 'Known for its mangrove forests, saltwater crocodiles, and rich biodiversity.' },
    ],
  },
  {
    id: 20,
    name: 'Punjab',
    description: 'The "Land of Five Rivers," heartland of the Sikh community, famous for the Golden Temple and rich cuisine.',
    longDescription: 'Punjab is a vibrant state with a rich history and culture. It is home to the Golden Temple, the holiest shrine in Sikhism. The state is known for its fertile lands, hearty cuisine, and energetic Bhangra music.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/punjab/400/300',
    topTouristPlaces: [
        { name: 'Golden Temple (Harmandir Sahib)', description: 'The holiest shrine in Sikhism, located in Amritsar.' },
        { name: 'Wagah Border', description: 'The border crossing between India and Pakistan, famous for its daily Beating Retreat ceremony.' },
        { name: 'Jallianwala Bagh', description: 'A public garden in Amritsar housing a memorial of national importance.' },
        { name: 'Chandigarh', description: 'The modern and well-planned joint capital, with attractions like the Rock Garden and Sukhna Lake.' },
        { name: 'Anandpur Sahib', description: 'A principal holy place for Sikhs, known for its gurdwaras and the Virasat-e-Khalsa museum.' },
        { name: 'Patiala', description: 'A former princely state known for its palaces like Qila Mubarak and traditional crafts.' },
        { name: 'Virasat-e-Khalsa', description: 'A museum of Sikhism located in the holy town of Anandpur Sahib.' },
        { name: 'Sheesh Mahal, Patiala', description: 'The "Palace of Mirrors," part of the old Moti Bagh Palace.' },
        { name: 'Kila Raipur Sports Festival', description: 'Known as the "Rural Olympics," held annually near Ludhiana.' },
        { name: 'Harike Wetland and Bird Sanctuary', description: 'The largest wetland in northern India, a major hub for migratory birds.' },
    ],
  },
  {
    id: 21,
    name: 'Rajasthan',
    description: 'The "Land of Kings," famous for its majestic forts, opulent palaces, and vast Thar Desert.',
    longDescription: 'Rajasthan is a land of royal grandeur, with magnificent forts and palaces in cities like Jaipur, Udaipur, and Jodhpur. It offers a vibrant culture, colorful festivals, and unique desert experiences.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/rajasthan/400/300',
    topTouristPlaces: [
        { name: 'Jaipur', description: 'The "Pink City," with attractions like Hawa Mahal, Amer Fort, and City Palace.' },
        { name: 'Udaipur', description: 'The "City of Lakes," known for its romantic Lake Pichola and majestic City Palace.' },
        { name: 'Jodhpur', description: 'The "Blue City," dominated by the massive Mehrangarth Fort.' },
        { name: 'Jaisalmer', description: 'The "Golden City," with its living fort, desert safaris, and sand dunes.' },
        { name: 'Pushkar', description: 'A holy town with a famous Brahma Temple and an annual camel fair.' },
        { name: 'Ranthambore National Park', description: 'One of the best places in India to spot tigers in the wild.' },
        { name: 'Mount Abu', description: 'The only hill station in Rajasthan, known for the Dilwara Jain Temples.' },
        { name: 'Bikaner', description: 'A desert city known for Junagarh Fort and the Karni Mata Temple (Rat Temple).' },
        { name: 'Chittorgarh Fort', description: 'A massive UNESCO World Heritage Site, symbolizing Rajput pride and valor.' },
        { name: 'Ajmer Sharif Dargah', description: 'A revered Sufi shrine in Ajmer, attracting devotees from all faiths.' },
    ],
  },
  {
    id: 22,
    name: 'Sikkim',
    description: 'A Himalayan wonderland, known for its pristine landscapes, Buddhist monasteries, and stunning mountain views.',
    longDescription: 'Sikkim is a small, beautiful state nestled in the Himalayas. It is known for its dramatic landscapes, including India\'s highest mountain, Kangchenjunga, and its serene Buddhist monasteries.',
    bestTimeToVisit: 'March to May, October to December',
    imageUrl: 'https://picsum.photos/seed/sikkim/400/300',
    topTouristPlaces: [
        { name: 'Gangtok', description: 'The vibrant capital, with attractions like MG Marg, Rumtek Monastery, and cable car rides.' },
        { name: 'Tsomgo Lake', description: 'A stunning glacial lake located at a high altitude, frozen during winter.' },
        { name: 'Nathula Pass', description: 'A mountain pass on the Indo-China border, offering breathtaking views.' },
        { name: 'Pelling', description: 'A small town with spectacular views of the Kangchenjunga peak and nearby monasteries.' },
        { name: 'Lachung, Lachen, and Yumthang Valley', description: 'Scenic villages and the "Valley of Flowers" in North Sikkim.' },
        { name: 'Rumtek Monastery', description: 'One of the largest and most significant monasteries in Sikkim.' },
        { name: 'Namchi', description: 'Known for its giant statues of Guru Padmasambhava and Lord Shiva, and the Char Dham replica.' },
        { name: 'Yuksom', description: 'The first capital of Sikkim and the base for many treks, including the one to Kangchenjunga.' },
        { name: 'Ravangla', description: 'A small tourist town with the famous Buddha Park.' },
        { name: 'Zuluk', description: 'A small village in a remote part of East Sikkim, famous for its winding roads and panoramic views.' },
    ],
  },
  {
    id: 23,
    name: 'Tamil Nadu',
    description: 'A land of ancient Dravidian culture, magnificent temples, classical dance, and delicious cuisine.',
    longDescription: 'Tamil Nadu is the cradle of Dravidian culture, evident in its towering, intricately carved temples. It also boasts beautiful hill stations, a long coastline, and is a center for classical Bharatanatyam dance.',
    bestTimeToVisit: 'November to February',
    imageUrl: 'https://picsum.photos/seed/tamilnadu/400/300',
    topTouristPlaces: [
        { name: 'Chennai', description: 'The capital city, known for Marina Beach, Kapaleeshwarar Temple, and colonial architecture.' },
        { name: 'Madurai', description: 'Home to the magnificent Meenakshi Amman Temple, a masterpiece of Dravidian architecture.' },
        { name: 'Mahabalipuram', description: 'A UNESCO World Heritage Site with ancient rock-cut temples and the Shore Temple.' },
        { name: 'Kanyakumari', description: 'The southernmost tip of mainland India, famous for its spectacular sunrises and sunsets.' },
        { name: 'Rameswaram', description: 'A holy island town with the Ramanathaswamy Temple, a major pilgrimage site.' },
        { name: 'Ooty', description: 'A popular hill station in the Nilgiri Hills, known for its toy train, gardens, and lakes.' },
        { name: 'Kodaikanal', description: 'The "Princess of Hill Stations," known for its serene lake, waterfalls, and forested valleys.' },
        { name: 'Thanjavur (Tanjore)', description: 'Famous for the Brihadeeswarar Temple, a UNESCO World Heritage Site.' },
        { name: 'Kanchipuram', description: 'The "City of a Thousand Temples," known for its grand temples and silk sarees.' },
        { name: 'Coimbatore', description: 'A major industrial city at the foothills of the Nilgiris, gateway to several tourist spots.' },
    ],
  },
  {
    id: 24,
    name: 'Telangana',
    description: 'The youngest state of India, with the bustling IT hub of Hyderabad and historic monuments.',
    longDescription: 'Telangana is a blend of old and new, with the historic city of Hyderabad at its heart, known for Charminar and Golconda Fort, alongside a thriving modern IT and pharmaceutical industry.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/telangana/400/300',
    topTouristPlaces: [
        { name: 'Hyderabad', description: 'The capital city, home to Charminar, Golconda Fort, Ramoji Film City, and delicious biryani.' },
        { name: 'Warangal', description: 'An ancient city with the Warangal Fort, Thousand Pillar Temple, and Ramappa Temple (UNESCO site).' },
        { name: 'Nagarjuna Sagar Dam', description: 'One of the largest dams in the world, built on the Krishna River.' },
        { name: 'Basara', description: 'Home to the Gnana Saraswati Temple, one of the few temples dedicated to the goddess of learning.' },
        { name: 'Bhongir Fort', description: 'A massive monolithic fort located on an isolated rock.' },
        { name: 'Medak Cathedral', description: 'The largest diocese in Asia and one of the most beautiful churches in India.' },
        { name: 'Kuntala Falls', description: 'The highest waterfall in Telangana, located in the Adilabad district.' },
        { name: 'Yadagirigutta', description: 'A popular Hindu temple dedicated to Narasimha Swamy, located on a hillock.' },
        { name: 'Alampur', description: 'A temple town on the banks of the Tungabhadra river, with ancient temples.' },
        { name: 'Pakhal Lake & Wildlife Sanctuary', description: 'A man-made lake and sanctuary near Warangal, rich in biodiversity.' },
    ],
  },
  {
    id: 25,
    name: 'Tripura',
    description: 'A hilly state in the northeast, known for its palaces, rock carvings, and rich cultural mix.',
    longDescription: 'Tripura is a small state with a rich history and a diverse ethnic population. It is known for its royal palaces like Ujjayanta Palace and the ancient rock sculptures of Unakoti.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/tripura/400/300',
    topTouristPlaces: [
        { name: 'Ujjayanta Palace', description: 'A magnificent former royal palace in Agartala, now serving as the State Museum.' },
        { name: 'Neermahal', description: 'The "Lake Palace" of Tripura, located in the middle of Rudrasagar Lake.' },
        { name: 'Unakoti', description: 'An ancient Shaivite pilgrimage site with huge rock-cut carvings of gods and goddesses.' },
        { name: 'Tripura Sundari Temple', description: 'One of the 51 Shakti Peethas, a revered Hindu pilgrimage site in Udaipur.' },
        { name: 'Sepahijala Wildlife Sanctuary', description: 'A wildlife sanctuary and academic research center with a zoo and botanical garden.' },
        { name: 'Jampui Hills', description: 'A hill range known for its pleasant climate, orange orchards, and panoramic views.' },
        { name: 'Agartala', description: 'The capital city, with its blend of natural beauty and cultural heritage.' },
        { name: 'Pilak', description: 'An archaeological site with artifacts from Buddhist and Hindu traditions.' },
        { name: 'Chabimura', description: 'Known for its panels of rock carvings on the steep mountain wall on the bank of Gomati river.' },
        { name: 'Dumboor Lake', description: 'A vast and picturesque water body with 48 islands, shaped like a small drum (damboor).' },
    ],
  },
  {
    id: 26,
    name: 'Uttar Pradesh',
    description: 'The heartland of India, home to the iconic Taj Mahal, the holy city of Varanasi, and rich history.',
    longDescription: 'Uttar Pradesh is a state of immense historical and religious importance. It is home to the Taj Mahal in Agra, the sacred Ganges river in Varanasi, and numerous sites associated with Hindu mythology.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/uttarpradesh/400/300',
    topTouristPlaces: [
        { name: 'Taj Mahal, Agra', description: 'A UNESCO World Heritage Site and one of the Seven Wonders of the World, an ivory-white marble mausoleum.' },
        { name: 'Varanasi', description: 'A holy city on the banks of the Ganges, known for its ghats, temples, and spiritual atmosphere.' },
        { name: 'Agra Fort', description: 'A historical fort in Agra, which served as the main residence of the Mughal Emperors.' },
        { name: 'Lucknow', description: 'The "City of Nawabs," known for its culture, cuisine, and historical monuments like Bara Imambara.' },
        { name: 'Fatehpur Sikri', description: 'A magnificent fortified ancient city, once the capital of the Mughal Empire.' },
        { name: 'Mathura & Vrindavan', description: 'The birthplace and childhood home of Lord Krishna, major pilgrimage sites for Hindus.' },
        { name: 'Prayagraj (Allahabad)', description: 'A holy city famous for the Triveni Sangam, the confluence of three rivers.' },
        { name: 'Sarnath', description: 'The place where Gautama Buddha first taught the Dharma after his enlightenment.' },
        { name: 'Ayodhya', description: 'The birthplace of Lord Rama, a major pilgrimage center.' },
        { name: 'Dudhwa National Park', description: 'A rich wildlife park known for its tigers, rhinos, and diverse ecosystems.' },
    ],
  },
  {
    id: 27,
    name: 'Uttarakhand',
    description: 'The "Land of the Gods," known for its Himalayan peaks, holy rivers, and major Hindu pilgrimage sites.',
    longDescription: 'Uttarakhand is a spiritual and adventure destination. It is home to the Char Dham pilgrimage sites, the holy city of Rishikesh (the yoga capital of the world), and stunning Himalayan trekking routes.',
    bestTimeToVisit: 'March to June, September to November',
    imageUrl: 'https://picsum.photos/seed/uttarakhand/400/300',
    topTouristPlaces: [
        { name: 'Rishikesh', description: 'The "Yoga Capital of the World," known for its ashrams, cafes, and adventure sports like river rafting.' },
        { name: 'Nainital', description: 'A popular hill station built around a pear-shaped lake, surrounded by mountains.' },
        { name: 'Mussoorie', description: 'The "Queen of the Hills," offering scenic views of the Himalayas.' },
        { name: 'Haridwar', description: 'A holy city where the Ganges river enters the plains, famous for the Ganga Aarti at Har Ki Pauri.' },
        { name: 'Auli', description: 'A premier skiing destination with stunning views of snow-capped peaks.' },
        { name: 'Jim Corbett National Park', description: 'India\'s oldest national park, a prime destination for tiger sightings.' },
        { name: 'Valley of Flowers National Park', description: 'A UNESCO World Heritage Site, known for its meadows of endemic alpine flowers.' },
        { name: 'Char Dham (Badrinath, Kedarnath, Gangotri, Yamunotri)', description: 'A set of four pilgrimage sites high in the Himalayas.' },
        { name: 'Dehradun', description: 'The capital city, with attractions like Robber\'s Cave and Sahastradhara.' },
        { name: 'Kausani', description: 'A hill station offering panoramic views of Himalayan peaks like Nanda Devi and Trishul.' },
    ],
  },
  {
    id: 28,
    name: 'West Bengal',
    description: 'Known for its rich literary and cultural heritage, the vibrant city of Kolkata, and the Sundarbans.',
    longDescription: 'West Bengal is a land of art, culture, and history. It is home to the intellectual hub of Kolkata, the Himalayan foothills of Darjeeling, and the unique mangrove ecosystem of the Sundarbans, home to the Bengal tiger.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/westbengal/400/300',
    topTouristPlaces: [
        { name: 'Kolkata', description: 'The "City of Joy," known for its colonial architecture, art galleries, and cultural festivals.' },
        { name: 'Darjeeling', description: 'A famous hill station known for its tea plantations, Himalayan Railway (Toy Train), and views of Kangchenjunga.' },
        { name: 'Sundarbans National Park', description: 'The largest mangrove forest in the world, a UNESCO site and home to the Bengal tiger.' },
        { name: 'Digha', description: 'A popular seaside resort town on the shores of the Bay of Bengal.' },
        { name: 'Shantiniketan', description: 'The university town founded by Rabindranath Tagore, a center for art and culture.' },
        { name: 'Kalimpong', description: 'A serene hill station with flower nurseries, Buddhist monasteries, and colonial-era architecture.' },
        { name: 'Bishnupur', description: 'Famous for its terracotta temples and Baluchari sarees.' },
        { name: 'Dooars', description: 'The floodplains of North-East India, known for their forests, wildlife sanctuaries, and tea gardens.' },
        { name: 'Murshidabad', description: 'A historical city on the banks of the Bhagirathi river, with palaces and mosques from the Nawab era.' },
        { name: 'Gaur', description: 'A ruined city with archaeological remains from the medieval period of Bengal.' },
    ],
  },
  {
    id: 29,
    name: 'Andaman & Nicobar',
    description: 'Emerald islands with stunning coral reefs, pristine beaches, and rich colonial history.',
    longDescription: 'The Andaman and Nicobar Islands are a remote archipelago in the Bay of Bengal, famous for their palm-lined, white-sand beaches, mangroves, and tropical rainforests. It\'s a paradise for diving and snorkeling, with vibrant coral reefs, and historical sites like the Cellular Jail.',
    bestTimeToVisit: 'October to May',
    imageUrl: 'https://picsum.photos/seed/andaman/400/300',
    topTouristPlaces: [
        { name: 'Havelock Island (Swaraj Dweep)', description: 'Famous for Radhanagar Beach, often ranked among the best beaches in Asia.' },
        { name: 'Cellular Jail', description: 'A colonial prison in Port Blair, now a national memorial, representing the struggles of Indian freedom fighters.' },
        { name: 'Neil Island (Shaheed Dweep)', description: 'Known for its serene beaches like Bharatpur, Laxmanpur, and Sitapur.' },
        { name: 'Ross Island (Netaji Subhas Chandra Bose Dweep)', description: 'The former administrative headquarters, now in ruins with a haunting beauty.' },
        { name: 'North Bay Island', description: 'Famous for its coral reefs and underwater activities like sea walking and snorkeling.' },
        { name: 'Baratang Island', description: 'Known for its natural wonders including limestone caves and mud volcanoes.' },
        { name: 'Diglipur', description: 'Home to Ross and Smith Islands, connected by a natural sandbar.' },
        { name: 'Jolly Buoy Island', description: 'Part of the Mahatma Gandhi Marine National Park, known for its rich marine life and coral reefs.' },
        { name: 'Elephant Beach', description: 'A pristine beach on Havelock Island, popular for snorkeling and other water sports.' },
        { name: 'Chidiya Tapu', description: 'Known as the "Bird Island," famous for its sunsets and birdwatching.' },
    ],
  },
  {
    id: 30,
    name: 'Chandigarh',
    description: 'India\'s first planned city, known for its modern architecture, urban design, and greenery.',
    longDescription: 'Designed by the modernist architect Le Corbusier, Chandigarh is a unique city known for its well-organized sectors, green spaces like the Rock Garden and Zakir Hussain Rose Garden, and clean environment. It serves as the capital for both Punjab and Haryana.',
    bestTimeToVisit: 'September to March',
    imageUrl: 'https://picsum.photos/seed/chandigarh/400/300',
    topTouristPlaces: [
        { name: 'Rock Garden', description: 'A unique sculpture garden created by Nek Chand, made from industrial and urban waste.' },
        { name: 'Sukhna Lake', description: 'A serene man-made lake at the foothills of the Himalayas, popular for boating and promenades.' },
        { name: 'Zakir Hussain Rose Garden', description: 'Asia\'s largest rose garden, with thousands of rose bushes of different varieties.' },
        { name: 'Capitol Complex', description: 'A UNESCO World Heritage Site designed by Le Corbusier, housing the government buildings.' },
        { name: 'Open Hand Monument', description: 'A symbolic structure designed by Le Corbusier, representing peace and prosperity.' },
        { name: 'Sector 17 Plaza', description: 'A major commercial center and a popular hub for shopping, dining, and cultural events.' },
        { name: 'Government Museum and Art Gallery', description: 'Home to a rich collection of Gandharan sculptures and miniature paintings.' },
        { name: 'Le Corbusier Centre', description: 'A museum dedicated to the life and works of the city\'s architect.' },
        { name: 'Japanese Garden', description: 'A beautifully landscaped park with Japanese-style pagodas, bridges, and water bodies.' },
        { name: 'Pinjore Gardens (Yadavindra Gardens)', description: 'A historic Mughal garden located near the city.' },
    ],
  },
  {
    id: 31,
    name: 'Daman & Diu and D&NH',
    description: 'A blend of Portuguese heritage, serene beaches, and lush green forests.',
    longDescription: 'This combined union territory on the western coast offers a unique mix of cultures. Daman and Diu boast beautiful beaches, historic forts, and charming Portuguese architecture, while Dadra and Nagar Haveli are known for their dense forests and tribal culture.',
    bestTimeToVisit: 'November to February',
    imageUrl: 'https://picsum.photos/seed/daman/400/300',
    topTouristPlaces: [
        { name: 'Diu Fort', description: 'A magnificent fort built by the Portuguese, offering panoramic views of the Arabian Sea.' },
        { name: 'Nagoa Beach, Diu', description: 'A beautiful and serene horse-shoe shaped beach.' },
        { name: 'Jampore Beach, Daman', description: 'A calm and picturesque beach, ideal for picnics and relaxation.' },
        { name: 'Vanganga Lake Garden, Silvassa', description: 'A beautiful garden with paddle boats, jogging tracks, and Japanese-style bridges.' },
        { name: 'St. Paul\'s Church, Diu', description: 'A stunning example of Baroque architecture, one of the most elaborate churches in India.' },
        { name: 'Tribal Cultural Museum, Silvassa', description: 'Showcases the history and culture of the tribal communities of the region.' },
        { name: 'Devka Beach, Daman', description: 'A popular beach with an amusement park and musical fountain.' },
        { name: 'Ghoghla Beach', description: 'One of the most beautiful beaches in Diu, known for its golden sands and clear waters.' },
        { name: 'Naida Caves', description: 'An intriguing network of interconnected caves and tunnels near Diu Fort.' },
        { name: 'Moti Daman Fort', description: 'A large fort in Daman with colonial-style buildings, a church, and a lighthouse.' },
    ],
  },
  {
    id: 32,
    name: 'Delhi (NCT)',
    description: 'The capital of India, a sprawling metropolis blending ancient history with modernity.',
    longDescription: 'Delhi, the National Capital Territory, is a city of contrasts. It\'s home to historical landmarks from the Mughal era like the Red Fort and Humayun\'s Tomb, alongside modern skyscrapers, bustling markets, and the seat of the Indian government.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/delhi/400/300',
    topTouristPlaces: [
        { name: 'India Gate', description: 'A war memorial dedicated to Indian soldiers, a prominent landmark of the city.' },
        { name: 'Qutub Minar', description: 'A UNESCO World Heritage Site, the tallest brick minaret in the world.' },
        { name: 'Humayun\'s Tomb', description: 'A magnificent tomb that was a precursor to the Taj Mahal, a fine example of Mughal architecture.' },
        { name: 'Red Fort', description: 'A historical fort that served as the main residence of the Mughal Emperors.' },
        { name: 'Lotus Temple', description: 'A Baháʼí House of Worship, notable for its flower-like shape.' },
        { name: 'Akshardham Temple', description: 'A massive temple complex showcasing Indian culture, spirituality, and architecture.' },
        { name: 'Connaught Place', description: 'A bustling commercial and financial hub with a circular design.' },
        { name: 'Chandni Chowk', description: 'One of the oldest and busiest markets in Old Delhi, famous for its food and shopping.' },
        { name: 'Rashtrapati Bhavan', description: 'The official residence of the President of India, an architectural marvel.' },
        { name: 'Lodhi Garden', description: 'A city park containing tombs, gardens, and historical monuments.' },
    ],
  },
  {
    id: 33,
    name: 'Jammu and Kashmir',
    description: 'Paradise on Earth, known for its stunning Himalayan landscapes, serene lakes, and houseboats.',
    longDescription: 'Jammu and Kashmir is renowned for its breathtaking natural beauty. From the picturesque valleys of Kashmir with its iconic Dal Lake to the spiritual shrines of Jammu, it\'s a destination that captivates every traveler with its alpine peaks and lush meadows.',
    bestTimeToVisit: 'April to October',
    imageUrl: 'https://picsum.photos/seed/jammuandkashmir/400/300',
    topTouristPlaces: [
        { name: 'Srinagar', description: 'Famous for Dal Lake, shikara rides, houseboats, and Mughal Gardens.' },
        { name: 'Gulmarg', description: 'A popular skiing destination and home to the world\'s second-highest operating cable car.' },
        { name: 'Pahalgam', description: 'A scenic town on the banks of the Lidder River, the starting point for the Amarnath Yatra.' },
        { name: 'Sonamarg', description: 'The "Meadow of Gold," known for its stunning landscapes and as a base for treks.' },
        { name: 'Vaishno Devi Temple', description: 'A major Hindu pilgrimage site located in Katra.' },
        { name: 'Patnitop', description: 'A hilltop tourist location offering panoramic views of the Shivalik range.' },
        { name: 'Jammu', description: 'The "City of Temples," with numerous shrines like Raghunath Temple and Bahu Fort.' },
        { name: 'Aru Valley', description: 'A pristine valley near Pahalgam, known for its scenic meadows and trekking opportunities.' },
        { name: 'Betaab Valley', description: 'A breathtaking valley with lush green meadows and the Lidder River flowing through it.' },
        { name: 'Sanasar', description: 'A cup-shaped meadow surrounded by coniferous trees, a hub for adventure activities.' },
    ],
  },
  {
    id: 34,
    name: 'Ladakh',
    description: 'A high-altitude desert region with dramatic landscapes, Buddhist monasteries, and adventure activities.',
    longDescription: 'Known as the "Land of High Passes," Ladakh is a cold desert in the Himalayas. It offers surreal landscapes, crystal-clear lakes like Pangong Tso, ancient Buddhist monasteries perched on hilltops, and thrilling opportunities for trekking and motorbiking.',
    bestTimeToVisit: 'June to September',
    imageUrl: 'https://picsum.photos/seed/ladakh/400/300',
    topTouristPlaces: [
        { name: 'Pangong Tso Lake', description: 'A stunning high-altitude saltwater lake that changes colors, located on the Indo-China border.' },
        { name: 'Nubra Valley', description: 'A high-altitude cold desert known for its sand dunes, double-humped camels, and Diskit Monastery.' },
        { name: 'Leh', description: 'The main town, with Leh Palace, Shanti Stupa, and a bustling market.' },
        { name: 'Tso Moriri Lake', description: 'A beautiful and serene high-altitude lake in the Changthang region.' },
        { name: 'Khardung La Pass', description: 'One of the highest motorable passes in the world, offering spectacular views.' },
        { name: 'Magnetic Hill', description: 'An optical illusion where vehicles appear to roll uphill against gravity.' },
        { name: 'Thiksey Monastery', description: 'A magnificent Tibetan Buddhist monastery resembling the Potala Palace in Lhasa.' },
        { name: 'Hemis National Park', description: 'The largest national park in South Asia, home to the elusive snow leopard.' },
        { name: 'Zanskar Valley', description: 'A remote and stunning valley, known for its adventurous treks, including the Chadar Trek on the frozen Zanskar River.' },
        { name: 'Lamayuru Monastery', description: 'One of the oldest and largest monasteries in Ladakh, known for its unique "lunar" landscape.' },
    ],
  },
  {
    id: 35,
    name: 'Lakshadweep',
    description: 'A tropical archipelago of 36 islands with pristine coral reefs and sun-kissed beaches.',
    longDescription: 'Lakshadweep is India\'s smallest union territory, a stunning chain of coral islands and atolls in the Laccadive Sea. It\'s a protected paradise, offering untouched beaches, turquoise lagoons, and some of the best snorkeling and scuba diving in the country.',
    bestTimeToVisit: 'October to May',
    imageUrl: 'https://picsum.photos/seed/lakshadweep/400/300',
    topTouristPlaces: [
        { name: 'Agatti Island', description: 'The gateway to Lakshadweep, with one of the most beautiful lagoons.' },
        { name: 'Bangaram Atoll', description: 'A breathtakingly beautiful tear-drop shaped island with pristine beaches and coral reefs.' },
        { name: 'Kavaratti', description: 'The capital, known for its beautiful mosques, marine aquarium, and water sports.' },
        { name: 'Minicoy Island', description: 'The southernmost island, known for its unique culture, lighthouse, and tuna canning factory.' },
        { name: 'Kadmat Island', description: 'A long and narrow island, famous for its marine turtles and excellent scuba diving sites.' },
        { name: 'Kalpeni Island', description: 'Known for its scenic beauty and the large storm bank of coral debris along its eastern shore.' },
        { name: 'Marine Museum, Kavaratti', description: 'Showcases a rich collection of marine life and artifacts.' },
        { name: 'Pitti Bird Sanctuary', description: 'An important nesting place for pelagic birds, declared a bird sanctuary.' },
        { name: 'Thinnakara Island', description: 'A tiny, uninhabited island near Bangaram, perfect for a peaceful day trip.' },
        { name: 'Amini Beach', description: 'Located on Amini Island, known for its serene environment and coral sandstone.' },
    ],
  },
  {
    id: 36,
    name: 'Puducherry',
    description: 'A charming coastal town with a distinct French colonial heritage, spiritual ashrams, and tranquil beaches.',
    longDescription: 'Puducherry, often called Pondy, retains a strong French influence in its architecture, streets, and culture. The French Quarter with its tree-lined boulevards and colonial villas, the spiritual serenity of Auroville, and its peaceful seaside promenade make it a unique destination.',
    bestTimeToVisit: 'October to March',
    imageUrl: 'https://picsum.photos/seed/puducherry/400/300',
    topTouristPlaces: [
        { name: 'Promenade Beach', description: 'A popular stretch of rocky beach with a beautiful walkway, ideal for morning and evening strolls.' },
        { name: 'Auroville', description: 'A universal township dedicated to human unity, with the Matrimandir at its center.' },
        { name: 'French Quarter (White Town)', description: 'Known for its colonial-style villas, tree-lined streets, and charming cafes.' },
        { name: 'Paradise Beach', description: 'A serene beach accessible by boat, known for its golden sands and clear waters.' },
        { name: 'Sri Aurobindo Ashram', description: 'A spiritual community founded by Sri Aurobindo, a major center for yoga and meditation.' },
        { name: 'Basilica of the Sacred Heart of Jesus', description: 'A beautiful Gothic-style church, a significant religious landmark.' },
        { name: 'Chunnambar Boat House', description: 'Offers boat rides on the backwaters, leading to Paradise Beach.' },
        { name: 'Manakula Vinayagar Temple', description: 'An ancient temple dedicated to Lord Ganesha, known for its resident elephant.' },
        { name: 'Serenity Beach', description: 'A quiet and beautiful beach, popular for surfing and relaxing.' },
        { name: 'Puducherry Museum', description: 'Houses a collection of rare sculptures from the Pallava and Chola dynasties, as well as artifacts from the Roman era.' },
    ],
  },
];